module.exports.RequestType = {
  LOGIN: "LOGIN",
  MY_PROFILE: "MY_PROFILE",
  MY_GROUP_LIST: "MY_GROUP_LIST"
};

module.exports.ResponseType = {
  FAIL: "RESPONSE_FAIL",
  LOGIN_OK: "RESPOINSE_LOGIN_OK",
  LOGIN_FAIL: "RESPONSE_LOGIN_FAIL",
  MY_PROFILE: "RESPONSE_MY_PROFILE",
  MY_GROUP_LIST: "RESPONSE_MY_GROUP_LIST"
};